package org.beehive.jitllm.backend.tornado.kernels;

import uk.ac.manchester.tornado.api.KernelContext;
import uk.ac.manchester.tornado.api.math.TornadoMath;
import uk.ac.manchester.tornado.api.types.HalfFloat;
import uk.ac.manchester.tornado.api.types.arrays.FloatArray;
import uk.ac.manchester.tornado.api.types.arrays.HalfFloatArray;
import uk.ac.manchester.tornado.api.types.arrays.IntArray;
import uk.ac.manchester.tornado.api.types.vectors.Half2;

/**
 * Llama batched-prefill KV kernels that address the cache through a block table.
 *
 * <p>The {@code Paged} twins of the batch-prefill kernels in {@link
 * TransformerBatchPrefillKernels}, differing from them in the KV index and nothing else — same
 * tiling, same online softmax, same barriers, same loop nest. Reviewing means diffing each against
 * its original.
 *
 * <p><b>These are one sequence's tokens, not several sequences.</b> Batched prefill processes
 * {@code batchSize} consecutive positions of a single sequence, so the base it replaces carries no
 * batch term either: {@code layerIndex * contextLength * kvDim + pos * kvDim}, with {@code pos}
 * varying per row. The slot is therefore still 0, and travels in {@code batchStartPosHolder[2]}
 * exactly as it travels in {@code positionHolder[1]} on the single-token path.
 *
 * <p>Addressing is defined once, in {@link KvBlockAddress}.
 *
 * <p><b>Generated by transformation, reviewed by hand</b>, like its single-token sibling {@link
 * TransformerPagedKvKernels}.
 */
public class TransformerPagedKvBatchPrefillKernels {

    public TransformerPagedKvBatchPrefillKernels() {}

    public static void batchedRopeWithKVCachePaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray wrapQBatch,
            FloatArray wrapKBatch,
            FloatArray wrapVBatch,
            FloatArray wrapKeyCache,
            FloatArray wrapValueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int globalIdx = context.globalIdx;
        int halfDim = dim / 2;
        int batchIdx = globalIdx / halfDim;
        int pairIdx = globalIdx % halfDim;
        int i = pairIdx * 2;

        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: see batchedRopeWithKVCachePacked
        }
        int pos = batchStartPosHolder.get(0) + batchIdx;
        int qOffset = batchIdx * dim;
        int kOffset = batchIdx * kvDim;

        if (i + 1 < dim) {
            int head_dim = i % headSize;
            // See batchedRopeWithKVCachePacked: frequencies belong to the model, not the kernel.
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q
            float v0q = wrapQBatch.get(qOffset + i);
            float v1q = wrapQBatch.get(qOffset + i + 1);
            wrapQBatch.set(qOffset + i, v0q * fcr - v1q * fci);
            wrapQBatch.set(qOffset + i + 1, v0q * fci + v1q * fcr);

            // Rotate K and write K,V to cache
            if (i + 1 < kvDim) {
                float v0k = wrapKBatch.get(kOffset + i);
                float v1k = wrapKBatch.get(kOffset + i + 1);
                float rotK0 = v0k * fcr - v1k * fci;
                float rotK1 = v0k * fci + v1k * fcr;
                wrapKBatch.set(kOffset + i, rotK0);
                wrapKBatch.set(kOffset + i + 1, rotK1);

                int cacheOff =
                        KvBlockAddress.offset(
                                blockTable,
                                batchStartPosHolder.get(2),
                                pos,
                                KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                wrapKeyCache.set(cacheOff + i, rotK0);
                wrapKeyCache.set(cacheOff + i + 1, rotK1);
                wrapValueCache.set(cacheOff + i, wrapVBatch.get(kOffset + i));
                wrapValueCache.set(cacheOff + i + 1, wrapVBatch.get(kOffset + i + 1));
            }
        }
    }

    // FP16-cache twin of batchedRopeWithKVCachePaged: identical arithmetic, the cache stored in
    // binary16.
    public static void batchedRopeWithKVCacheFP16Paged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray wrapQBatch,
            FloatArray wrapKBatch,
            FloatArray wrapVBatch,
            HalfFloatArray wrapKeyCache,
            HalfFloatArray wrapValueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int globalIdx = context.globalIdx;
        int halfDim = dim / 2;
        int batchIdx = globalIdx / halfDim;
        int pairIdx = globalIdx % halfDim;
        int i = pairIdx * 2;

        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: see batchedRopeWithKVCachePacked
        }
        int pos = batchStartPosHolder.get(0) + batchIdx;
        int qOffset = batchIdx * dim;
        int kOffset = batchIdx * kvDim;

        if (i + 1 < dim) {
            int head_dim = i % headSize;
            // See batchedRopeWithKVCachePacked: frequencies belong to the model, not the kernel.
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q
            float v0q = wrapQBatch.get(qOffset + i);
            float v1q = wrapQBatch.get(qOffset + i + 1);
            wrapQBatch.set(qOffset + i, v0q * fcr - v1q * fci);
            wrapQBatch.set(qOffset + i + 1, v0q * fci + v1q * fcr);

            // Rotate K and write K,V to cache
            if (i + 1 < kvDim) {
                float v0k = wrapKBatch.get(kOffset + i);
                float v1k = wrapKBatch.get(kOffset + i + 1);
                float rotK0 = v0k * fcr - v1k * fci;
                float rotK1 = v0k * fci + v1k * fcr;
                wrapKBatch.set(kOffset + i, rotK0);
                wrapKBatch.set(kOffset + i + 1, rotK1);

                int cacheOff =
                        KvBlockAddress.offset(
                                blockTable,
                                batchStartPosHolder.get(2),
                                pos,
                                KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                wrapKeyCache.set(cacheOff + i, new HalfFloat(rotK0));
                wrapKeyCache.set(cacheOff + i + 1, new HalfFloat(rotK1));
                wrapValueCache.set(cacheOff + i, new HalfFloat(wrapVBatch.get(kOffset + i)));
                wrapValueCache.set(
                        cacheOff + i + 1, new HalfFloat(wrapVBatch.get(kOffset + i + 1)));
            }
        }
    }

    public static void batchedRopeWithKVCachePackedPaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray qkvBatch,
            FloatArray wrapKeyCache,
            FloatArray wrapValueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int globalIdx = context.globalIdx;
        int halfDim = dim / 2;
        int batchIdx = globalIdx / halfDim;
        int pairIdx = globalIdx % halfDim;
        int i = pairIdx * 2;
        int qkvStride = dim + 2 * kvDim;

        // Rows past the chunk's real token count are padding: their contents are stale and their
        // positions can run past this layer's KV-cache slice (contextLength is the CLI's
        // --max-tokens), which would corrupt the next layer's keys and values.
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return;
        }

        int pos = batchStartPosHolder.get(0) + batchIdx;
        int qOffset = batchIdx * qkvStride;
        int kOffset = batchIdx * qkvStride + dim;
        int vOffset = batchIdx * qkvStride + dim + kvDim;

        if (i + 1 < dim) {
            // Frequencies come from the model's precomputed freq_cis tables (its own rope_theta,
            // plus any Llama 3.1 scaling). A base compiled into the kernel was wrong for
            // Llama-3.2 (50000 vs 500000) and, once the decode path was corrected, also left
            // prefill and decode rotating differently.
            int head_dim = i % headSize;
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q in place
            float v0q = qkvBatch.get(qOffset + i);
            float v1q = qkvBatch.get(qOffset + i + 1);
            qkvBatch.set(qOffset + i, v0q * fcr - v1q * fci);
            qkvBatch.set(qOffset + i + 1, v0q * fci + v1q * fcr);

            // Rotate K and write K,V to cache
            if (i + 1 < kvDim) {
                float v0k = qkvBatch.get(kOffset + i);
                float v1k = qkvBatch.get(kOffset + i + 1);
                float rotK0 = v0k * fcr - v1k * fci;
                float rotK1 = v0k * fci + v1k * fcr;

                int cacheOff =
                        KvBlockAddress.offset(
                                blockTable,
                                batchStartPosHolder.get(2),
                                pos,
                                KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                wrapKeyCache.set(cacheOff + i, rotK0);
                wrapKeyCache.set(cacheOff + i + 1, rotK1);
                wrapValueCache.set(cacheOff + i, qkvBatch.get(vOffset + i));
                wrapValueCache.set(cacheOff + i + 1, qkvBatch.get(vOffset + i + 1));
            }
        }
    }

    public static void batchedRopeWithKVCachePackedFP16Paged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray qkvBatch,
            HalfFloatArray wrapKeyCache,
            HalfFloatArray wrapValueCache,
            FloatArray freqCisReal,
            FloatArray freqCisImag,
            int kvDim,
            int headSize,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int globalIdx = context.globalIdx;
        int halfDim = dim / 2;
        int batchIdx = globalIdx / halfDim;
        int pairIdx = globalIdx % halfDim;
        int i = pairIdx * 2;
        int qkvStride = dim + 2 * kvDim;

        // Same padding rule as batchedRopeWithKVCachePacked: rows past the chunk's real token
        // count are stale and their positions can run past this layer's KV-cache slice.
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return;
        }

        int pos = batchStartPosHolder.get(0) + batchIdx;
        int qOffset = batchIdx * qkvStride;
        int kOffset = batchIdx * qkvStride + dim;
        int vOffset = batchIdx * qkvStride + dim + kvDim;

        if (i + 1 < dim) {
            // Frequencies come from the model, not the kernel — see batchedRopeWithKVCachePacked.
            int head_dim = i % headSize;
            int freqIdx = pos * (headSize / 2) + (head_dim / 2);
            float fcr = freqCisReal.get(freqIdx);
            float fci = freqCisImag.get(freqIdx);

            // Rotate Q in place
            float v0q = qkvBatch.get(qOffset + i);
            float v1q = qkvBatch.get(qOffset + i + 1);
            qkvBatch.set(qOffset + i, v0q * fcr - v1q * fci);
            qkvBatch.set(qOffset + i + 1, v0q * fci + v1q * fcr);

            // Rotate K and write K,V to the half-precision cache
            if (i + 1 < kvDim) {
                float v0k = qkvBatch.get(kOffset + i);
                float v1k = qkvBatch.get(kOffset + i + 1);
                float rotK0 = v0k * fcr - v1k * fci;
                float rotK1 = v0k * fci + v1k * fcr;

                int cacheOff =
                        KvBlockAddress.offset(
                                blockTable,
                                batchStartPosHolder.get(2),
                                pos,
                                KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg),
                                kvDim,
                                blockCfg,
                                blockStride);
                wrapKeyCache.setHalf2(cacheOff + i, Half2.fromFloats(rotK0, rotK1));
                wrapValueCache.setHalf2(
                        cacheOff + i,
                        Half2.fromFloats(qkvBatch.get(vOffset + i), qkvBatch.get(vOffset + i + 1)));
            }
        }
    }

    /** Simdgroups per (query row, head) in {@link #batchedFlashAttentionSimdPaged}. */
    public static final int FLASH_SIMDGROUPS = 8;

    /**
     * Batched-prefill twin of {@code
     * TransformerPagedKvKernels.processHeadsFlashAttentionSimdPaged}: one threadgroup of {@link
     * #FLASH_SIMDGROUPS} 32-lane simdgroups per (batch row, head), each simdgroup walking the row's
     * causal positions {@code g, g + G, ...} with an online softmax of its own, lanes owning head
     * dimensions, partial results merged once in threadgroup memory. Same arguments and layout as
     * {@link #batchedFlashAttentionPaged}. Worker: {@code batch * nHeads} groups of {@code 32 *
     * FLASH_SIMDGROUPS} threads. Needs {@code headSize % 32 == 0} and {@code headSize <= 128}.
     */
    public static void batchedFlashAttentionSimdPaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray wrapQBatch,
            FloatArray wrapKeyCache,
            FloatArray wrapValueCache,
            FloatArray wrapXbBatch,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: no real query, and its KV range is not valid
        }
        int sg = tid >> 5;
        int lane = tid & 31;

        float[] sMax = context.allocateFloatLocalArray(FLASH_SIMDGROUPS);
        float[] sSum = context.allocateFloatLocalArray(FLASH_SIMDGROUPS);
        float[] sAcc = context.allocateFloatLocalArray(FLASH_SIMDGROUPS * headSize);

        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadOffset = (h / kvMul) * headSize;
        int qBase = batchIdx * dim + h * headSize;
        float scale = 1.0f / TornadoMath.sqrt(headSize);

        int d0 = lane;
        int d1 = lane + 32;
        int d2 = lane + 64;
        int d3 = lane + 96;
        float q0 = wrapQBatch.get(qBase + d0) * scale;
        float q1 = d1 < headSize ? wrapQBatch.get(qBase + d1) * scale : 0.0f;
        float q2 = d2 < headSize ? wrapQBatch.get(qBase + d2) * scale : 0.0f;
        float q3 = d3 < headSize ? wrapQBatch.get(qBase + d3) * scale : 0.0f;

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        float a0 = 0.0f;
        float a1 = 0.0f;
        float a2 = 0.0f;
        float a3 = 0.0f;
        for (int t = sg; t <= pos; t += FLASH_SIMDGROUPS) {
            int base =
                    KvBlockAddress.offset(
                                    blockTable, slot, t, layerOff, kvDim, blockCfg, blockStride)
                            + kvHeadOffset;
            float partial = q0 * wrapKeyCache.get(base + d0);
            if (d1 < headSize) {
                partial += q1 * wrapKeyCache.get(base + d1);
            }
            if (d2 < headSize) {
                partial += q2 * wrapKeyCache.get(base + d2) + q3 * wrapKeyCache.get(base + d3);
            }
            float score = context.simdSum(partial);
            float newMax = TornadoMath.max(maxScore, score);
            float correction = TornadoMath.exp(maxScore - newMax);
            float weight = TornadoMath.exp(score - newMax);
            sumExp = sumExp * correction + weight;
            a0 = a0 * correction + weight * wrapValueCache.get(base + d0);
            if (d1 < headSize) {
                a1 = a1 * correction + weight * wrapValueCache.get(base + d1);
            }
            if (d2 < headSize) {
                a2 = a2 * correction + weight * wrapValueCache.get(base + d2);
                a3 = a3 * correction + weight * wrapValueCache.get(base + d3);
            }
            maxScore = newMax;
        }

        if (lane == 0) {
            sMax[sg] = maxScore;
            sSum[sg] = sumExp;
        }
        int accBase = sg * headSize;
        sAcc[accBase + d0] = a0;
        if (d1 < headSize) {
            sAcc[accBase + d1] = a1;
        }
        if (d2 < headSize) {
            sAcc[accBase + d2] = a2;
            sAcc[accBase + d3] = a3;
        }
        context.localBarrier();

        for (int d = tid; d < headSize; d += context.localGroupSizeX) {
            float globalMax = Float.NEGATIVE_INFINITY;
            for (int g = 0; g < FLASH_SIMDGROUPS; g++) {
                globalMax = TornadoMath.max(globalMax, sMax[g]);
            }
            float total = 0.0f;
            float out = 0.0f;
            for (int g = 0; g < FLASH_SIMDGROUPS; g++) {
                float w = TornadoMath.exp(sMax[g] - globalMax);
                total += sSum[g] * w;
                out += sAcc[g * headSize + d] * w;
            }
            wrapXbBatch.set(qBase + d, out / total);
        }
    }

    public static void batchedFlashAttentionPaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray wrapQBatch,
            FloatArray wrapKeyCache,
            FloatArray wrapValueCache,
            FloatArray wrapXbBatch,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int localSz = context.localGroupSizeX;

        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: no real query, and its KV range is not valid
        }
        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_C = 16;

        float[] qShared = context.allocateFloatLocalArray(headSize);
        float[] kTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] vTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] sTile = context.allocateFloatLocalArray(BLOCK_C);
        float[] maxHolder = context.allocateFloatLocalArray(1);

        // Load Q into shared memory
        int qOffset = batchIdx * dim + h * headSize;
        for (int i = tid; i < headSize; i += localSz) {
            qShared[i] = wrapQBatch.get(qOffset + i);
        }
        context.localBarrier();

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        float[] output = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            output[i] = 0.0f;
        }

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_C) {
            int tileEnd = Math.min(tileC + BLOCK_C - 1, pos);

            // Load K/V tile
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                int tileMOff = tInTile * headSize;
                // The block walk depends on the position, not on d, so it is computed once
                // per position. Keeping it inside the loop — where the legacy line that
                // computed loff + pos*kvDim + d sat — costs a table load and an integer
                // divide per element, which measured -7.3% on Qwen2 Q8_0.
                int kvBase =
                        KvBlockAddress.offset(
                                        blockTable, slot, t, layerOff, kvDim, blockCfg, blockStride)
                                + kvHeadIdx * headSize;
                for (int d = 0; d < headSize; d++) {
                    kTile[tileMOff + d] = wrapKeyCache.get(kvBase + d);
                    vTile[tileMOff + d] = wrapValueCache.get(kvBase + d);
                }
            }
            context.localBarrier();

            // Compute attention scores
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += qShared[d] * kTile[tInTile * headSize + d];
                }
                sTile[tInTile] = score / TornadoMath.sqrt(headSize);
            }
            context.localBarrier();

            // Tile max
            float tileMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t <= tileEnd - tileC; t++) {
                if (sTile[t] > tileMax) {
                    tileMax = sTile[t];
                }
            }
            if (tid == 0) {
                maxHolder[0] = tileMax;
            }
            context.localBarrier();
            float curTileMax = maxHolder[0];

            float newMax = Math.max(maxScore, curTileMax);
            if (newMax != maxScore && maxScore != Float.NEGATIVE_INFINITY) {
                float scale = TornadoMath.exp(maxScore - newMax);
                sumExp *= scale;
                for (int d = 0; d < headSize; d++) {
                    output[d] *= scale;
                }
            }
            maxScore = newMax;

            for (int t = 0; t <= tileEnd - tileC; t++) {
                float expScore = TornadoMath.exp(sTile[t] - maxScore);
                sumExp += expScore;
                for (int d = 0; d < headSize; d++) {
                    output[d] += expScore * vTile[t * headSize + d];
                }
            }
            context.localBarrier();
        }

        float norm = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        int xbOffset = batchIdx * dim + h * headSize;
        for (int d = tid; d < headSize; d += localSz) {
            wrapXbBatch.set(xbOffset + d, output[d] * norm);
        }
    }

    // FP16-cache twin of batchedFlashAttentionPaged: identical arithmetic, the cache stored in
    // binary16.
    public static void batchedFlashAttentionKVFP16Paged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray wrapQBatch,
            HalfFloatArray wrapKeyCache,
            HalfFloatArray wrapValueCache,
            FloatArray wrapXbBatch,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int localSz = context.localGroupSizeX;

        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: no real query, and its KV range is not valid
        }
        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_C = 16;

        float[] qShared = context.allocateFloatLocalArray(headSize);
        float[] kTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] vTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] sTile = context.allocateFloatLocalArray(BLOCK_C);
        float[] maxHolder = context.allocateFloatLocalArray(1);

        // Load Q into shared memory
        int qOffset = batchIdx * dim + h * headSize;
        for (int i = tid; i < headSize; i += localSz) {
            qShared[i] = wrapQBatch.get(qOffset + i);
        }
        context.localBarrier();

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        float[] output = new float[headSize];
        for (int i = 0; i < headSize; i++) {
            output[i] = 0.0f;
        }

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_C) {
            int tileEnd = Math.min(tileC + BLOCK_C - 1, pos);

            // Load K/V tile
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                int tileMOff = tInTile * headSize;
                // The block walk depends on the position, not on d, so it is computed once
                // per position. Keeping it inside the loop — where the legacy line that
                // computed loff + pos*kvDim + d sat — costs a table load and an integer
                // divide per element, which measured -7.3% on Qwen2 Q8_0.
                int kvBase =
                        KvBlockAddress.offset(
                                        blockTable, slot, t, layerOff, kvDim, blockCfg, blockStride)
                                + kvHeadIdx * headSize;
                for (int d = 0; d < headSize; d++) {
                    kTile[tileMOff + d] = wrapKeyCache.get(kvBase + d).getFloat32();
                    vTile[tileMOff + d] = wrapValueCache.get(kvBase + d).getFloat32();
                }
            }
            context.localBarrier();

            // Compute attention scores
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += qShared[d] * kTile[tInTile * headSize + d];
                }
                sTile[tInTile] = score / TornadoMath.sqrt(headSize);
            }
            context.localBarrier();

            // Tile max
            float tileMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t <= tileEnd - tileC; t++) {
                if (sTile[t] > tileMax) {
                    tileMax = sTile[t];
                }
            }
            if (tid == 0) {
                maxHolder[0] = tileMax;
            }
            context.localBarrier();
            float curTileMax = maxHolder[0];

            float newMax = Math.max(maxScore, curTileMax);
            if (newMax != maxScore && maxScore != Float.NEGATIVE_INFINITY) {
                float scale = TornadoMath.exp(maxScore - newMax);
                sumExp *= scale;
                for (int d = 0; d < headSize; d++) {
                    output[d] *= scale;
                }
            }
            maxScore = newMax;

            for (int t = 0; t <= tileEnd - tileC; t++) {
                float expScore = TornadoMath.exp(sTile[t] - maxScore);
                sumExp += expScore;
                for (int d = 0; d < headSize; d++) {
                    output[d] += expScore * vTile[t * headSize + d];
                }
            }
            context.localBarrier();
        }

        float norm = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        int xbOffset = batchIdx * dim + h * headSize;
        for (int d = tid; d < headSize; d += localSz) {
            wrapXbBatch.set(xbOffset + d, output[d] * norm);
        }
    }

    public static void batchedFlashAttentionFP16OutPaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray qkvBatch,
            FloatArray wrapKeyCache,
            FloatArray wrapValueCache,
            HalfFloatArray attnOutFP16,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int localSz = context.localGroupSizeX;

        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return; // padding row: no real query, and its KV range is not valid
        }
        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_C = 16;
        int qkvStride = dim + 2 * kvDim;

        float[] qShared = context.allocateFloatLocalArray(headSize);
        float[] kTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] vTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] sTile = context.allocateFloatLocalArray(BLOCK_C);

        // Load Q (rotated, from the packed QKV buffer) into shared memory
        int qOffset = batchIdx * qkvStride + h * headSize;
        for (int i = tid; i < headSize; i += localSz) {
            qShared[i] = qkvBatch.get(qOffset + i);
        }
        context.localBarrier();

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        // Each thread owns output dims d0 = tid and (if headSize > localSz) d1.
        float acc0 = 0.0f;
        float acc1 = 0.0f;
        int d1 = tid + localSz;

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_C) {
            int tileEnd = Math.min(tileC + BLOCK_C - 1, pos);
            int tileLen = tileEnd - tileC + 1;

            // Load K/V tile — flattened over (t, d) for coalescing
            for (int idx = tid; idx < tileLen * headSize; idx += localSz) {
                int tInTile = idx / headSize;
                int d = idx % headSize;
                int kvOff =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tileC + tInTile,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize
                                + d;
                kTile[tInTile * headSize + d] = wrapKeyCache.get(kvOff);
                vTile[tInTile * headSize + d] = wrapValueCache.get(kvOff);
            }
            context.localBarrier();

            // Scores: one thread per key position in the tile
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += qShared[d] * kTile[tInTile * headSize + d];
                }
                sTile[tInTile] = score / TornadoMath.sqrt(headSize);
            }
            context.localBarrier();

            // Tile max: redundant per-thread scan over <= 16 shared values —
            // deterministic across the workgroup, no broadcast needed.
            float tileMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < tileLen; t++) {
                if (sTile[t] > tileMax) {
                    tileMax = sTile[t];
                }
            }

            float newMax = Math.max(maxScore, tileMax);
            if (maxScore != Float.NEGATIVE_INFINITY && newMax != maxScore) {
                float corr = TornadoMath.exp(maxScore - newMax);
                sumExp *= corr;
                acc0 *= corr;
                acc1 *= corr;
            }
            maxScore = newMax;

            for (int t = 0; t < tileLen; t++) {
                float p = TornadoMath.exp(sTile[t] - maxScore);
                sumExp += p;
                acc0 += p * vTile[t * headSize + tid];
                if (d1 < headSize) {
                    acc1 += p * vTile[t * headSize + d1];
                }
            }
            context.localBarrier();
        }

        float norm = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        int outOffset = batchIdx * dim + h * headSize;
        attnOutFP16.set(outOffset + tid, new HalfFloat(acc0 * norm));
        if (d1 < headSize) {
            attnOutFP16.set(outOffset + d1, new HalfFloat(acc1 * norm));
        }
    }

    public static void batchedFlashAttentionFP16OutKVFP16Paged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray qkvBatch,
            HalfFloatArray wrapKeyCache,
            HalfFloatArray wrapValueCache,
            HalfFloatArray attnOutFP16,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int localSz = context.localGroupSizeX;

        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        // Padding row: no real query, and its key/value range was never allocated, so the
        // paged reads below would address blocks this slot does not own. batchIdx comes from
        // groupIdx, so the whole workgroup takes this branch together and the localBarrier()s
        // further down are still reached uniformly.
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return;
        }

        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_C = 16;
        int qkvStride = dim + 2 * kvDim;
        int halfHead = headSize / 2;

        float[] qShared = context.allocateFloatLocalArray(headSize);
        float[] kTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] vTile = context.allocateFloatLocalArray(BLOCK_C * headSize);
        float[] sTile = context.allocateFloatLocalArray(BLOCK_C);

        // Load Q (rotated, from the packed QKV buffer) into shared memory
        int qOffset = batchIdx * qkvStride + h * headSize;
        for (int i = tid; i < headSize; i += localSz) {
            qShared[i] = qkvBatch.get(qOffset + i);
        }
        context.localBarrier();

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        float acc0 = 0.0f;
        float acc1 = 0.0f;
        int d1 = tid + localSz;

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_C) {
            int tileEnd = Math.min(tileC + BLOCK_C - 1, pos);
            int tileLen = tileEnd - tileC + 1;

            // Load K/V tile — one packed 32-bit load per thread per pair of head dims
            for (int idx = tid; idx < tileLen * halfHead; idx += localSz) {
                int tInTile = idx / halfHead;
                int dPair = (idx % halfHead) * 2;
                int kvOff =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tileC + tInTile,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize
                                + dPair;
                Half2 kPair = wrapKeyCache.getHalf2(kvOff);
                Half2 vPair = wrapValueCache.getHalf2(kvOff);
                int tileOff = tInTile * headSize + dPair;
                kTile[tileOff] = Half2.lowFloat(kPair);
                kTile[tileOff + 1] = Half2.highFloat(kPair);
                vTile[tileOff] = Half2.lowFloat(vPair);
                vTile[tileOff + 1] = Half2.highFloat(vPair);
            }
            context.localBarrier();

            // Scores: one thread per key position in the tile
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                float score = 0.0f;
                for (int d = 0; d < headSize; d++) {
                    score += qShared[d] * kTile[tInTile * headSize + d];
                }
                sTile[tInTile] = score / TornadoMath.sqrt(headSize);
            }
            context.localBarrier();

            float tileMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < tileLen; t++) {
                if (sTile[t] > tileMax) {
                    tileMax = sTile[t];
                }
            }

            float newMax = Math.max(maxScore, tileMax);
            if (maxScore != Float.NEGATIVE_INFINITY && newMax != maxScore) {
                float corr = TornadoMath.exp(maxScore - newMax);
                sumExp *= corr;
                acc0 *= corr;
                acc1 *= corr;
            }
            maxScore = newMax;

            for (int t = 0; t < tileLen; t++) {
                float p = TornadoMath.exp(sTile[t] - maxScore);
                sumExp += p;
                acc0 += p * vTile[t * headSize + tid];
                if (d1 < headSize) {
                    acc1 += p * vTile[t * headSize + d1];
                }
            }
            context.localBarrier();
        }

        float norm = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        int outOffset = batchIdx * dim + h * headSize;
        attnOutFP16.set(outOffset + tid, new HalfFloat(acc0 * norm));
        if (d1 < headSize) {
            attnOutFP16.set(outOffset + d1, new HalfFloat(acc1 * norm));
        }
    }

    public static void batchedFlashAttentionFP16OutKVFP16PackedTilePaged(
            KernelContext context,
            IntArray batchStartPosHolder,
            FloatArray qkvBatch,
            HalfFloatArray wrapKeyCache,
            HalfFloatArray wrapValueCache,
            HalfFloatArray attnOutFP16,
            int nHeads,
            int headSize,
            int kvDim,
            int kvMul,
            int layerIndex,
            IntArray blockTable,
            int blockCfg,
            int blockStride,
            int dim) {
        int tid = context.localIdx;
        int groupId = context.groupIdx;
        int localSz = context.localGroupSizeX;

        int batchIdx = groupId / nHeads;
        int h = groupId % nHeads;
        // Padding row: no real query, and its key/value range was never allocated, so the
        // paged reads below would address blocks this slot does not own. batchIdx comes from
        // groupIdx, so the whole workgroup takes this branch together and the localBarrier()s
        // further down are still reached uniformly.
        if (batchIdx >= batchStartPosHolder.get(1)) {
            return;
        }

        int pos = batchStartPosHolder.get(0) + batchIdx;
        int slot = batchStartPosHolder.get(2);
        int layerOff = KvBlockAddress.layerOffset(layerIndex, kvDim, blockCfg);
        int kvHeadIdx = h / kvMul;
        int BLOCK_C = 16;
        int qkvStride = dim + 2 * kvDim;
        int halfHead = headSize / 2;

        Half2[] qPacked = context.allocateHalf2LocalArray(64); // headSize/2 <= 64
        Half2[] kTile = context.allocateHalf2LocalArray(16 * 64); // BLOCK_C * halfHead
        Half2[] vTile = context.allocateHalf2LocalArray(16 * 64);
        float[] sTile = context.allocateFloatLocalArray(BLOCK_C);

        // Load Q (rotated, from the packed QKV buffer) into shared memory as packed pairs
        int qOffset = batchIdx * qkvStride + h * headSize;
        for (int i = tid; i < halfHead; i += localSz) {
            qPacked[i] =
                    Half2.fromFloats(
                            qkvBatch.get(qOffset + i * 2), qkvBatch.get(qOffset + i * 2 + 1));
        }
        context.localBarrier();

        float maxScore = Float.NEGATIVE_INFINITY;
        float sumExp = 0.0f;
        float acc0 = 0.0f;
        float acc1 = 0.0f;
        int d1 = tid + localSz;

        for (int tileC = 0; tileC <= pos; tileC += BLOCK_C) {
            int tileEnd = Math.min(tileC + BLOCK_C - 1, pos);
            int tileLen = tileEnd - tileC + 1;

            // Load K/V tile — packed 32-bit load into a packed __half2 tile, no expansion
            for (int idx = tid; idx < tileLen * halfHead; idx += localSz) {
                int tInTile = idx / halfHead;
                int dPair = idx % halfHead;
                int kvOff =
                        KvBlockAddress.offset(
                                        blockTable,
                                        slot,
                                        tileC + tInTile,
                                        layerOff,
                                        kvDim,
                                        blockCfg,
                                        blockStride)
                                + kvHeadIdx * headSize
                                + dPair * 2;
                int tileOff = tInTile * halfHead + dPair;
                kTile[tileOff] = wrapKeyCache.getHalf2(kvOff);
                vTile[tileOff] = wrapValueCache.getHalf2(kvOff);
            }
            context.localBarrier();

            // Scores: one thread per key position; one __hfma2 per pair, expanded once per row
            for (int t = tileC + tid; t <= tileEnd; t += localSz) {
                int tInTile = t - tileC;
                Half2 scoreAcc = Half2.fromFloats(0.0f, 0.0f);
                for (int dp = 0; dp < halfHead; dp++) {
                    scoreAcc = Half2.fma(kTile[tInTile * halfHead + dp], qPacked[dp], scoreAcc);
                }
                sTile[tInTile] =
                        (Half2.lowFloat(scoreAcc) + Half2.highFloat(scoreAcc))
                                / TornadoMath.sqrt(headSize);
            }
            context.localBarrier();

            float tileMax = Float.NEGATIVE_INFINITY;
            for (int t = 0; t < tileLen; t++) {
                if (sTile[t] > tileMax) {
                    tileMax = sTile[t];
                }
            }

            float newMax = Math.max(maxScore, tileMax);
            if (maxScore != Float.NEGATIVE_INFINITY && newMax != maxScore) {
                float corr = TornadoMath.exp(maxScore - newMax);
                sumExp *= corr;
                acc0 *= corr;
                acc1 *= corr;
            }
            maxScore = newMax;

            // P·V: each thread owns fixed head dims (tid, tid+localSz), so its lane within
            // the packed pair is fixed; select low/high once per tile element.
            int pair0 = tid >> 1;
            boolean high0 = (tid & 1) == 1;
            int pair1 = d1 >> 1;
            boolean high1 = (d1 & 1) == 1;
            for (int t = 0; t < tileLen; t++) {
                float p = TornadoMath.exp(sTile[t] - maxScore);
                sumExp += p;
                Half2 v0 = vTile[t * halfHead + pair0];
                acc0 += p * (high0 ? Half2.highFloat(v0) : Half2.lowFloat(v0));
                if (d1 < headSize) {
                    Half2 v1 = vTile[t * halfHead + pair1];
                    acc1 += p * (high1 ? Half2.highFloat(v1) : Half2.lowFloat(v1));
                }
            }
            context.localBarrier();
        }

        float norm = (sumExp > 0.0f) ? (1.0f / sumExp) : 0.0f;
        int outOffset = batchIdx * dim + h * headSize;
        attnOutFP16.set(outOffset + tid, new HalfFloat(acc0 * norm));
        if (d1 < headSize) {
            attnOutFP16.set(outOffset + d1, new HalfFloat(acc1 * norm));
        }
    }
}
